namespace WeaponAugs.Common
{
	public enum AugType : byte
	{
		None = 0,
		Might = 1,
		Force = 2,
		Precision = 3,
		Rush = 4,
		Armorbane = 5,
		Titanreach = 6,
		Dire = 7,
		Heartsurge = 8,
		Arcana = 9,
		Frenzy = 10,
		Battlelust = 11,
		Conservation = 12,
		Overflow = 13,
		Fortune = 14,
		Ignite = 15,
		Taint = 16,
		Ballistic = 17,
		Finisher = 18,
		Unleash = 19,
		Combobreak = 20,
		Deathecho = 21,
		Lightweight = 22,
		Revitalize = 23,
		Megastrike = 24,
		Sturdy = 25,
		Barrage = 26,
		Diversion = 27,
		Wildstrike = 28,
		Uplifting = 29,
		Luck = 30,
		Rend = 31,
		Deathshroud = 32,
		Ward = 33,
		Minicrit = 34,
		Siphon = 35,
		Paincycle = 36,
		Rally = 37,
		Blast = 38,
		Superluck = 39,
		Kingslayer = 40,
		Hypercrit = 41,
		Unstable = 42,
		Vigor = 43,
		Determination = 44,
		Breaker = 45,
		Reaping = 46,
		Overdrive = 47,
		Ultracutter = 48,
		Voidic = 49,
		Committed = 50,
		Lifeleech = 51,
		Radiance = 52,
		Relentless = 53,
		Momentum = 54,
		Collateral = 55,
		Supercharge = 56,
		Execution = 57,
		Resurgence = 58,
		Runic = 59,
		Powertheft = 60,
		Count // Placeholder value as a means of easy retrival of the amount of items in this enum
	}

	public enum AugTier : byte
	{
		None = 0,
		Basic = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Ultimate = 5,
        Count // Placeholder value as a means of easy retrival of the amount of items in this enum
    }
}
